"""Score the live Qwen pilot batch (2026-07-28) for the TIP x scope-resilience test.

Reads Johann's real, live-generated Qwen answers from D:\\mandala\\Qwentest.txt
(format: "CASE{n}:" blocks each containing "A0:"/"A1:"/"A2:"/"A3:" sections
- A0 is Qwen's reaction to the CONTEXT block alone, before any probe; A1/A2/A3
are the live answers to PROBE 1/2/3 respectively, given in the SAME chat so
each answer could see the previous one, as instructed).

Unlike scripts/real_session_tip_scope_test.py's replay agent (constant
tip_score=1.0 because the "response" was fixed before any perturbation
existed), these A1/A2/A3 answers were generated by Qwen AFTER seeing the
(perturbed) CONTEXT block - a genuine live-generation-at-perturbation-time
response, addressing exactly the limitation identified in that run's
epistemic_status.md entry.

rho_sem values are looked up from real_session_tip_scope_results.json
(already computed for these same conversation_index/domain/bucket
combinations) rather than recomputed, to keep the structural encoding
identical across both runs.

Privacy: reads Johann's own real (Qwen-generated, not personal-message)
text in-process; only derived/aggregate values are written to the output
JSON, no raw text.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from scipy import stats

from genesis_tip.harness.session_runner import ContextEntry, SessionMode, SessionRunner
from genesis_tip.metrics.consistency_scorer import ConsistencyScore, score_session

QWEN_FILE = Path(r"D:\mandala\Qwentest.txt")
MANIFEST_FILE = Path(r"C:\Users\Privat\.claude\jobs\dc9d7823\tmp\qwen_test_manifest.json")
PRIOR_RESULTS_FILE = Path(
    r"D:\mandala\genesis-tip\.claude\worktrees\genesis-tip-empirical-test\scripts\real_session_tip_scope_results.json"
)

# Rebuild the exact same context_entries/probes used to generate the batch
import sys  # noqa: E402

sys.path.insert(0, r"D:\mandala\genesis-tip\.claude\worktrees\genesis-tip-empirical-test\scripts")
import real_session_tip_scope_test as builder  # noqa: E402


def parse_qwen_file(path: Path) -> dict[int, dict[str, str]]:
    text = path.read_text(encoding="utf-8")
    case_blocks = re.split(r"\nCASE(\d+):\n", "\n" + text)
    # re.split with a capturing group yields [pre, num1, block1, num2, block2, ...]
    cases: dict[int, dict[str, str]] = {}
    for i in range(1, len(case_blocks), 2):
        case_num = int(case_blocks[i])
        block = case_blocks[i + 1]
        answers: dict[str, str] = {}
        parts = re.split(r"\n(A[0-3]):\n", "\n" + block)
        for j in range(1, len(parts), 2):
            label = parts[j]
            body = parts[j + 1].strip()
            answers[label] = body
        cases[case_num] = answers
    return cases


def derive_scalar_score(score: ConsistencyScore) -> float:
    if score.n_turns == 0:
        return 0.0
    n_issues = score.self_reference_inconsistency_count + len(score.contradiction_pairs)
    return max(0.0, 1.0 - min(1.0, n_issues / score.n_turns))


def main() -> None:
    qwen_cases = parse_qwen_file(QWEN_FILE)
    manifest = json.loads(MANIFEST_FILE.read_text())
    prior = json.loads(PRIOR_RESULTS_FILE.read_text())
    rho_lookup = {
        (p["conversation_index"], p["perturbation_mode"]): p["rho_sem"] for p in prior["pairs"]
    }

    with open(builder.CONVERSATIONS_PATH, encoding="utf-8") as f:
        data = json.load(f)

    results = []
    for entry in manifest:
        case_num = entry["case"]
        conv_idx = entry["conversation_index"]
        mode = entry["mode"]
        qwen_answers = qwen_cases.get(case_num)
        if qwen_answers is None:
            print(f"WARNING: case {case_num} not found in Qwen file, skipping")
            continue
        replies = [qwen_answers.get(f"A{i}", "") for i in (1, 2, 3)]
        if not all(replies):
            print(f"WARNING: case {case_num} missing A1/A2/A3, skipping")
            continue

        conv = data[conv_idx]
        msgs = builder.flatten_conversation(conv)
        context_msgs = msgs[: builder.N_CONTEXT_ENTRIES]
        context_entries = [
            ContextEntry(
                timestamp=__import__("datetime").datetime.fromtimestamp(m.create_time).isoformat(),
                content=m.text,
                entry_type=m.role,
            )
            for m in context_msgs
        ]
        rest = msgs[builder.N_CONTEXT_ENTRIES :]
        probe_pairs = []
        j = 0
        while j < len(rest) - 1 and len(probe_pairs) < builder.N_PROBES:
            if rest[j].role == "user" and rest[j + 1].role == "assistant":
                probe_pairs.append(rest[j].text)
                j += 2
            else:
                j += 1
        probes = probe_pairs

        turn_counter = {"n": 0}

        def live_agent(messages: list[dict[str, str]], _replies=replies, _tc=turn_counter) -> str:
            idx = _tc["n"]
            _tc["n"] += 1
            return _replies[idx] if idx < len(_replies) else _replies[-1]

        if mode == "shuffle":
            manipulator = lambda entries: builder.temporal_shuffle(entries)  # noqa: E731
        elif mode == "gap":
            manipulator = lambda entries: builder.gap_injection(entries)  # noqa: E731
        elif mode == "contradict":
            spec = builder.build_contradiction_spec(context_entries)
            if spec is None:
                print(f"WARNING: case {case_num} (contradict) - no number found, skipping")
                continue
            manipulator = lambda entries, _s=spec: builder.contradiction_injection(entries, _s)  # noqa: E731
        else:
            continue

        runner = SessionRunner(
            agent_fn=live_agent,
            mode=SessionMode.FRAGMENTED,
            agent_id="qwen-live-pilot",
            manipulator=manipulator,
        )
        result = runner.run(context_entries, probes)
        score = score_session(result)
        tip_score = derive_scalar_score(score)
        rho_sem = rho_lookup.get((conv_idx, mode))

        results.append(
            {
                "case": case_num,
                "conversation_index": conv_idx,
                "perturbation_mode": mode,
                "tip_score": tip_score,
                "rho_sem": rho_sem,
                "consistency_breakdown": score.summary_dict(),
                "has_a0": "A0" in qwen_answers,
            }
        )
        print(
            f"Case {case_num:2d} (conv#{conv_idx}, {mode:10s}): "
            f"tip_score={tip_score:.4f}  rho_sem={rho_sem}"
        )

    n = len(results)
    print(f"\nn = {n} live-scored pairs")
    if n >= 3:
        tip_arr = [r["tip_score"] for r in results]
        rho_arr = [r["rho_sem"] for r in results]
        correlation, p_value = stats.spearmanr(rho_arr, tip_arr)
        print(f"Spearman rho = {correlation:.4f}")
        print(f"p-value      = {p_value:.4e}")
        THRESHOLD, MIN_N = 0.3, 30
        if n < MIN_N:
            verdict = "INSUFFICIENT_SAMPLE"
        elif correlation >= THRESHOLD:
            verdict = "SUPPORTED"
        else:
            verdict = "FALSIFIED"
        print(f"Verdict (n<{MIN_N} so formally insufficient, reported anyway): {verdict}")
    else:
        correlation = p_value = None
        verdict = "INSUFFICIENT_SAMPLE"

    out = {
        "data_source": "D:/mandala/Qwentest.txt (live Qwen answers, pilot batch)",
        "n_pairs_scored": n,
        "spearman_rho": correlation,
        "p_value": p_value,
        "verdict": verdict,
        "min_sample_size_note": (
            "pre-registered n>=30 not reached (pilot batch, n=8) - directional only"
        ),
        "results": results,
    }
    out_path = Path(__file__).parent / "qwen_live_pilot_results.json"
    out_path.write_text(json.dumps(out, indent=2))
    print(f"\nSaved: {out_path}")


if __name__ == "__main__":
    main()
